/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally auto-generated by `next dev` / `next build`.
// It's committed here as a placeholder so the project type-checks cleanly
// even before the first build. Do not edit by hand.
